### PR TITLE
Update config and folders

### PR DESCRIPTION
**Pull request by gidesan**
@nicpuddu could make sense rename `ui` folder to `components`? having presentational component, container components but not styles could be a better match

### CODE REVIEW

**Comment by gReis89** [comment]
All changes looks good to me except by the __test__ folder. Creating a folder to handle unit tests doesn't look right to me, basically, unit tests will target a single file which makes sense putting this files together. Also, when we have a situation like u did: `components/__test__` u will exclude the testable files inside `../api` and `../state`, so or we create `__test__` folder inside of these two, or put or `__test__` folder right after the `./src` and replicate our folder structure there, both ways doesn't looks good to me.

here's a very objective article about this:
https://medium.com/@JeffLombardJr/organizing-tests-in-jest-17fc431ff850

**Comment by nicpuddu** [comment]
> All changes looks good to me except by the **test** folder. Creating a folder to handle unit tests doesn't look right to me, basically, unit tests will target a single file which makes sense putting this files together. Also, when we have a situation like u did: `components/__test__` u will exclude the testable files inside `../api` and `../state`, so or we create `__test__` folder inside of these two, or put or `__test__` folder right after the `./src` and replicate our folder structure there, both ways doesn't looks good to me.
> 
> here's a very objective article about this:
> https://medium.com/@JeffLombardJr/organizing-tests-in-jest-17fc431ff850
> 
> but at the end, it is all personal preferences, so if the majority of the team vote for the `__test__` folder, I'm okay with that =]

I believe it was probably not well explained in our notes, but there should be not a single __test__ directory, there should be one in each directory containing the files you want to have tested.

i.e.

- state/reducerNameDirectory contains:
reducer.js
actions.js
types.js
selectors.js
__tests__ directory containing reducer.test.js etc etc...

and the same applies for every directory containing a file that needs testing

**Comment by nicpuddu** [comment]
> @nicpuddu could make sense rename `ui` folder to `components`? having presentational component, container components but not styles could be a better match

fine with me

**Comment by gReis89** [comment]
Can we get rid of the `public/manifest.json` to stop the below console error? 
Screen Shot 2019-09-17 at 9 53 05 AM

I guess the `robots.txt` can be gone too

**Comment by gidesan** [comment]
just set the PR to WIP so I can fix that manifest.json issue and test out a new eslint plugin

**Pull request merged**
